#!/usr/bin/env python

import json
import transaction
from persistent.mapping import PersistentMapping
from persistent.list import PersistentList

from common import db_setup


def load_json(fname):
    fd = open(fname, 'r')
    data = fd.read().decode('utf-8')
    return json.loads(data)


def load_data(fname, root_node):
    json_data = load_json(fname)
    root_node['data'] = PersistentList()
    for d in json_data:
        root_node['data'].append(PersistentMapping(d))

if __name__ == '__main__':
    _, root_node = db_setup()
    ## Load sample generated by http://www.generatedata.com/
    load_data('media/dataSep-7-2014.json', root_node)
    transaction.commit()
    import ipdb; ipdb.set_trace()
